
[env:esp32-c3-devkitc-02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	adafruit/Adafruit BME280 Library @ ^2.3.0
	adafruit/DHT sensor library @ ^1.4.7
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	knolleary/PubSubClient @ ^2.8


monitor_speed = 115200
